### PR TITLE
Add `auth` support and proper `create-user` errand

### PR DESCRIPTION
**Pull request by janaurka**
Mainly this PR introduces `auth` support for MongoDb.

To get `auth` running, the following steps are required:

1. Keep mongodb.auth.enable disabled (read: set it to false)
2. Deploy mongodb
3. Run errand replset to create the cluster
4. Run errand create-user to create an user to auth
5. Change mongodb.auth.enable to true
6. Update the deployment

Also this PR makes the whole `bosh` release way more flexible, since it allows settings various stuff (and also puts them into the according `spec` files).

### CODE REVIEW

**Comment by huangered** [comment]
@janaurka  very good pr, we will test it

**Comment by janaurka** [comment]
@huangered: please note that i’ve added some more enhancements.

The `replset` errend was using hardcoded IP and so on.

Maybe it would make sense to make the `creat-user` errand support multiple roles and/or multiple users.

**Comment by janaurka** [comment]
Well, now it’s pretty much up and running.

With this you can create a `replica-set` of `n`-servers.

Also the `create-user` errand was refactored and is now `create-admin-user` because it creates an `admin` user which can be used for something like this: https://github.com/spring-cloud-samples/cloudfoundry-service-broker

**Comment by linlynn** [comment]
thanks @janaurka  . Did you test this pr in your local environment ?

**Comment by janaurka** [comment]
Hey

Yeah, it's up and running with auth + replica set enabled. But I guess the question implies that there is s problem and/or something is not clear?

Cheers

On March 20, 2017 3:09:27 AM GMT+01:00, Lynn Lin <notifications@github.com> wrote:
>thanks @janaurka  . Did you test this pr in your local environment ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cloudfoundry-community/mongodb-bosh-release/pull/1#issuecomment-287666859

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by linlynn** [comment]
@janaurka   I am seeing below issues when create replset 

lynn@dev:~/mongodb-bosh-release$ bosh run errand
1. replset
2. create-admin-user
Choose an errand: 1
Acting as user 'admin' on deployment 'mongodb3' on 'my-bosh'

Director task 168
  Started preparing deployment > Preparing deployment

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

     Done preparing deployment > Preparing deployment (00:00:00)

  Started creating missing vms > replset/b5ae7435-459d-4299-adf1-218b7b8ee570 (0). Done (00:02:41)

  Started updating instance replset > replset/b5ae7435-459d-4299-adf1-218b7b8ee570 (0) (canary). Done (00:00:37)

  Started running errand > replset/0. Done (00:00:37)

  Started fetching logs for replset/b5ae7435-459d-4299-adf1-218b7b8ee570 (0) > Finding and packing log files. Done (00:00:01)

Task 168 done

Started         2017-03-20 12:43:38 UTC
Finished        2017-03-20 12:47:34 UTC
Duration        00:03:56

[stdout]
None

[stderr]
Traceback (most recent call last):
  File "/var/vcap/jobs/replset/bin/replset.py", line 24, in <module>
    c.admin.command("replSetInitiate",config)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 478, in command
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 748, in _socket_for_reads
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 712, in _get_socket
  File "build/bdist.linux-x86_64/egg/pymongo/topology.py", line 141, in select_server
  File "build/bdist.linux-x86_64/egg/pymongo/topology.py", line 117, in select_servers
pymongo.errors.ServerSelectionTimeoutError: 10.241.143.45:27017: [Errno 111] Connection refused
---------------------------------------------------------------------------------------------------------------

However I am able to connect 10.241.143.45:27017 (one mongodb instance ) successfully

**Comment by linlynn** [comment]
dig into more and find the issue happen when initialize replset 


[stderr]
Traceback (most recent call last):
  File "/var/vcap/jobs/replset/bin/replset.py", line 24, in <module>
    c.admin.command("replSetInitiate",config)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 481, in command
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 393, in _command
  File "build/bdist.linux-x86_64/egg/pymongo/pool.py", line 211, in command
  File "build/bdist.linux-x86_64/egg/pymongo/network.py", line 100, in command
  File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 196, in _check_command_response
pymongo.errors.OperationFailure: command SON([('replSetInitiate', {'_id': 'resp1', 'members': [{'host': '10.241.143.45:27017', '_id': 0}, {'host': '10.241.143.46:27017', '_id': 1}, {'host': '10.241.143.47:27017', '_id': 2}]})]) on namespace admin.$cmd failed: replSetInitiate quorum check failed because not all proposed set members responded affirmatively: 10.241.143.47:27017 failed with Connection refused

**Comment by janaurka** [comment]
sorry, was on vacation. 

`[Errno 111] Connection refused`  seems to be pretty clear. What it does, it tries to connect to one of the `MongoDB` instances using `HAProxy` (and the default port there is `27027` whyever this is the case). 

```
MongoClient("<%= p('haproxy.mongodb.ip') %>", <%= p('haproxy.mongodb.port.frontend') %>)
```

I assume that you try to connect to it using the `actual` port which the `MongoDB`s are using behind the LB and not the LB port. Can you check this quickly?

**Comment by janaurka** [comment]
@linlynn : did you get it working?

**Comment by linlynn** [comment]
@janaurka it works , Previously  my network environment mess up

**Pull request merged**
